export const GET_LIST_USER_REQUEST = "GET_LIST_USER_REQUEST";
export const GET_LIST_USER_SUCCESS = "GET_LIST_USER_SUCCESS";
export const GET_LIST_USER_FAILURE = "GET_LIST_USER_FAILURE";

export const GET_DETAIL_USER_REQUEST = "GET_DETAIL_USER_REQUEST";
export const GET_DETAIL_USER_SUCCESS = "GET_DETAIL_USER_SUCCESS";
export const GET_DETAIL_USER_FAILURE = "GET_DETAIL_USER_FAILURE";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILURE = "DELETE_USER_FAILURE";

export const GET_PROFILE_USER_REQUEST = "GET_PROFILE_USER_REQUEST";
export const GET_PROFILE_USER_SUCCESS = "GET_PROFILE_USER_SUCCESS";
export const GET_PROFILE_USER_FAILURE = "GET_PROFILE_USER_FAILURE";

export const UPDATE_PROFILE_USER_REQUEST = "UPDATE_PROFILE_USER_REQUEST";
export const UPDATE_PROFILE_USER_SUCCESS = "UPDATE_PROFILE_USER_SUCCESS";
export const UPDATE_PROFILE_USER_FAILURE = "UPDATE_PROFILE_USER_FAILURE";
