export const GET_BRAND_REQUEST = "GET_BRAND_REQUEST";
export const GET_BRAND_SUCCESS = "GET_BRAND_SUCCESS";
export const GET_BRAND_FAILURE = "GET_BRAND_FAILURE";

export const GET_LIST_BRAND_REQUEST = "GET_LIST_BRAND_REQUEST";
export const GET_LIST_BRAND_SUCCESS = "GET_LIST_BRAND_SUCCESS";
export const GET_LIST_BRAND_FAILURE = "GET_LIST_BRAND_FAILURE";

export const GET_DETAIL_BRAND_REQUEST = "GET_DETAIL_BRAND_REQUEST";
export const GET_DETAIL_BRAND_SUCCESS = "GET_DETAIL_BRAND_SUCCESS";
export const GET_DETAIL_BRAND_FAILURE = "GET_DETAIL_BRAND_FAILURE";

export const CREATE_BRAND_REQUEST = "CREATE_BRAND_REQUEST";
export const CREATE_BRAND_SUCCESS = "CREATE_BRAND_SUCCESS";
export const CREATE_BRAND_FAILURE = "CREATE_BRAND_FAILURE";

export const UPDATE_BRAND_REQUEST = "UPDATE_BRAND_REQUEST";
export const UPDATE_BRAND_SUCCESS = "UPDATE_BRAND_SUCCESS";
export const UPDATE_BRAND_FAILURE = "UPDATE_BRAND_FAILURE";

export const DELETE_BRAND_REQUEST = "DELETE_BRAND_REQUEST";
export const DELETE_BRAND_SUCCESS = "DELETE_BRAND_SUCCESS";
export const DELETE_BRAND_FAILURE = "DELETE_BRAND_FAILURE";
