export const GET_PRODUCT_REQUEST = "GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAILURE = "GET_PRODUCT_FAILURE";

export const GET_LIST_PRODUCT_REQUEST = "GET_LIST_PRODUCT_REQUEST";
export const GET_LIST_PRODUCT_SUCCESS = "GET_LIST_PRODUCT_SUCCESS";
export const GET_LIST_PRODUCT_FAILURE = "GET_LIST_PRODUCT_FAILURE";

export const GET_DETAIL_PRODUCT_REQUEST = "GET_DETAIL_PRODUCT_REQUEST";
export const GET_DETAIL_PRODUCT_SUCCESS = "GET_DETAIL_PRODUCT_SUCCESS";
export const GET_DETAIL_PRODUCT_FAILURE = "GET_DETAIL_PRODUCT_FAILURE";

export const GET_DETAIL_ID_PRODUCT_REQUEST = "GET_DETAIL_ID_PRODUCT_REQUEST";
export const GET_DETAIL_ID_PRODUCT_SUCCESS = "GET_DETAIL_ID_PRODUCT_SUCCESS";
export const GET_DETAIL_ID_PRODUCT_FAILURE = "GET_DETAIL_ID_PRODUCT_FAILURE";

export const GET_PRODUCT_FILTER_REQUEST = "GET_PRODUCT_FILTER_REQUEST";
export const GET_PRODUCT_FILTER_SUCCESS = "GET_PRODUCT_FILTER_SUCCESS";
export const GET_PRODUCT_FILTER_FAILURE = "GET_PRODUCT_FILTER_FAILURE";

export const GET_PRODUCT_BRAND_REQUEST = "GET_PRODUCT_BRAND_REQUEST";
export const GET_PRODUCT_BRAND_SUCCESS = "GET_PRODUCT_BRAND_SUCCESS";
export const GET_PRODUCT_BRAND_FAILURE = "GET_PRODUCT_BRAND_FAILURE";

export const SEARCH_NAME_PRODUCT_REQUEST = "SEARCH_NAME_PRODUCT_REQUEST";
export const SEARCH_NAME_PRODUCT_SUCCESS = "SEARCH_NAME_PRODUCT_SUCCESS";
export const SEARCH_NAME_PRODUCT_FAILURE = "SEARCH_NAME_PRODUCT_FAILURE";

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAILURE = "CREATE_PRODUCT_FAILURE";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILURE = "UPDATE_PRODUCT_FAILURE";

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";
