export const GET_LIST_NEWS_REQUEST = "GET_LIST_NEWS_REQUEST";
export const GET_LIST_NEWS_SUCCESS = "GET_LIST_NEWS_SUCCESS";
export const GET_LIST_NEWS_FAILURE = "GET_LIST_NEWS_FAILURE";

export const GET_NEWS_REQUEST = "GET_NEWS_REQUEST";
export const GET_NEWS_SUCCESS = "GET_NEWS_SUCCESS";
export const GET_NEWS_FAILURE = "GET_NEWS_FAILURE";

export const GET_DETAIL_NEWS_REQUEST = "GET_DETAIL_NEWS_REQUEST";
export const GET_DETAIL_NEWS_SUCCESS = "GET_DETAIL_NEWS_SUCCESS";
export const GET_DETAIL_NEWS_FAILURE = "GET_DETAIL_NEWS_FAILURE";

export const GET_NEWS_ID_REQUEST = "GET_NEWS_ID_REQUEST";
export const GET_NEWS_ID_SUCCESS = "GET_NEWS_ID_SUCCESS";
export const GET_NEWS_ID_FAILURE = "GET_NEWS_ID_FAILURE";

export const CREATE_NEWS_REQUEST = "CREATE_NEWS_REQUEST";
export const CREATE_NEWS_SUCCESS = "CREATE_NEWS_SUCCESS";
export const CREATE_NEWS_FAILURE = "CREATE_NEWS_FAILURE";

export const UPDATE_NEWS_REQUEST = "UPDATE_NEWS_REQUEST";
export const UPDATE_NEWS_SUCCESS = "UPDATE_NEWS_SUCCESS";
export const UPDATE_NEWS_FAILURE = "UPDATE_NEWS_FAILURE";

export const DELETE_NEWS_REQUEST = "DELETE_NEWS_REQUEST";
export const DELETE_NEWS_SUCCESS = "DELETE_NEWS_SUCCESS";
export const DELETE_NEWS_FAILURE = "DELETE_NEWS_FAILURE";
